ST-1386 trigger wait for downstream pipeline
Signed-off-by: Matteo Di Carlo <matteo.dicarlo@inaf.it>

diff --git a/.gitlab-ci.yml b/.gitlab-ci.yml
--- a/.gitlab-ci.yml
+++ b/.gitlab-ci.yml
@@ -56,19 +56,37 @@ trigger-ska-tango-examples:
   stage: test
   script:
     - |
-      VERS=$(make show-version RELEASE_CONTEXT_DIR=images/ska-tango-images-pytango-builder);
-      export BUILD_IMAGE="${CI_REGISTRY}/${CI_PROJECT_NAMESPACE}/${CI_PROJECT_NAME}/ska-tango-images-pytango-builder:${VERS}";
-      VERS=$(make show-version RELEASE_CONTEXT_DIR=images/ska-tango-images-pytango-runtime);
-      export BASE_IMAGE="${CI_REGISTRY}/${CI_PROJECT_NAMESPACE}/${CI_PROJECT_NAME}/ska-tango-images-pytango-runtime:${VERS}";
+      VERS=$(make show-version RELEASE_CONTEXT_DIR=images/ska-tango-images-pytango-builder)
+      export BUILD_IMAGE="${CI_REGISTRY}/${CI_PROJECT_NAMESPACE}/${CI_PROJECT_NAME}/ska-tango-images-pytango-builder:${VERS}"
+      VERS=$(make show-version RELEASE_CONTEXT_DIR=images/ska-tango-images-pytango-runtime)
+      export BASE_IMAGE="${CI_REGISTRY}/${CI_PROJECT_NAMESPACE}/${CI_PROJECT_NAME}/ska-tango-images-pytango-runtime:${VERS}"
       export OCI_BUILD_ADDITIONAL_ARGS="--no-cache --build-arg BUILD_IMAGE --build-arg BASE_IMAGE "
-      curl --request POST \
+      response=$(curl --request POST \
            --form token=$CI_JOB_TOKEN \
            --form ref=master \
            --form "variables[BUILD_IMAGE]=${BUILD_IMAGE}" \
            --form "variables[BASE_IMAGE]=${BASE_IMAGE}" \
            --form "variables[OCI_BUILD_ADDITIONAL_ARGS]=${OCI_BUILD_ADDITIONAL_ARGS}" \
            --form "variables[SKA_PYTHON_PYTANGO_BUILDER_IMAGE]=${BUILD_IMAGE}" \
-           "https://gitlab.com/api/v4/projects/9673989/trigger/pipeline"
+           "https://gitlab.com/api/v4/projects/9673989/trigger/pipeline")
+      resource_name=$(echo "$resource_id" | rev | cut -d "/" -f 1 | rev)
+      echo "Created pipeline for '${resource_name}':"
+      echo "$(jq -r '.web_url' <<< "$response")"
+      pipeline_id=$(jq -r '.id' <<< "$response")
+      pipeline_url="https://gitlab.com/api/v4/projects/9673989/pipelines/${pipeline_id}"
+      for i in {1..5}
+      do
+        response=$(curl -s --header "PRIVATE-TOKEN: $CI_JOB_TOKEN" "$pipeline_url")
+        status=$(jq -r '.status' <<< "$response")
+        if [[ $status == "success" ]]; then
+          echo "Pipeline for '${resource}' succeeded: ${pipeline_url}"
+        elif [[ $status == "failed" ]]; then
+          echo "Pipeline for '${resource}' failed: ${pipeline_url}"
+          exit 1
+        else
+          sleep 5
+        fi
+      done
 
 .tango-dependencies_rules:
   rules:
